### ISSUE TITLE
Propuesta de estructura 

### ISSUE THREAD

**Issue by Enaraque** [spmanolo/calidad-aire#9]
Hola @spmanolo, he estado pensando en la estructura que se puede llevar a cabo para este problema. Creo que lo mejor seria hacer 3 clases, 2 serían objetos valor y la otra sería la entidad. Te comento a continuación:

### Clase Localizacion
Esta clase estaría relacionada con la zona que se desea que el usuario introduzca, tal y como se comento en ambas historias de usuario, tanto para la persona con alergia #5 como para la periodista #6.

### Clase MedicionesDeContaminacion
Esta clase hará referencia a los valores de diferentes métricas que nos aporta la [Junta de Andalucía](https://www.juntadeandalucia.es/medioambiente/atmosfera/informes_siva/cuantitativo/) en cada archivo `csv`.

### Clase CalidadDelAire

Esta sería la clase principal donde se harían todos los cálculos necesarios con los valores de contaminación obtenidos en una zona y día concreto. 

## Datos adicionales

Creo que es necesario destacar la falta de una clase `Fecha` ya que también se comenta en ambas Historias de Usuario. Esta clase no será necesaria gracias a que `TypeScript` cuenta con el tipo `Date` el cual cuenta con todo lo necesario para referirnos a la fecha que deseamos.

## Comentarios

Toda esta estructura está planteada desde mi punto de vista, es decir, me puedes comentar cualquier detalle que crees que puede ser mejor opción o una ayuda adicional para el desarrollo de la estructura para que así podamos avanzar con la mejor solución en este objetivo. Un saludo 😄

**Comment by spmanolo** [comment]
Hola @Enaraque, veo genial esta estructura, es una buena idea crear a parte las clases `Localización` y `MedicionesDeContaminacion`, para tenerlo todo bien modularizado. Y el tema de la clase `Fecha` efectivamente no creo que hiciera falta por lo que comentas.
Buen trabajo :+1: :smile:

**Comment by Enaraque** [comment]
Perfecto! En cuanto pueda te creo los issues relacionados con cada clase para ir explicando los atributos que tendrían y me vas comentando que te parecen 🔨

**Comment by spmanolo** [comment]
Genial :)
